spring.application.name=askgt
server.port = 4445

#database information
spring.datasource.url=jdbc:postgresql://localhost:5432/askgt?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=password

